schema_version = "1.0.0"

id = "tracking_toolkit"
version = "2.0.0"
name = "Tracking Toolkit"
tagline = "Use OpenXR trackers and devices directly in Blender"
maintainer = "Ethan Porcaro <ethan@varrett.com>"
tags = ["Animation", "Tracking"]

type = "add-on"
blender_version_min = "5.0.0"
platforms = ["windows-x64"]

license = [
    "SPDX:GPL-3.0-or-later",
]

wheels = [
    "./wheels/pyopenxr-1.1.5301-py3-none-any.whl",
    "./wheels/pyopengl-3.1.10-py3-none-any.whl"
]

[build]
paths_exclude_pattern = [
  "images/",  # Stuff for readme
  "__pycache__/",
  ".*",
  "*.zip",
  "repository_base.json",
  "DEVELOPMENT.md",
  "README.md",
  "requirements.txt",
  "requirements.dev.txt"
]

[permissions]
files = "Load custom shapes for tracker models"