schema_version = "1.0.0"

id = "tracking_toolkit"
version = "2.0.0"
name = "Tracking Toolkit"
tagline = "Use OpenXR trackers and devices directly in Blender"
maintainer = "Ethan Porcaro <ethan@varrett.com>"
tags = ["Animation", "Tracking"]

type = "add-on"
blender_version_min = "4.2.0"
platforms = ["windows-x64", "linux-x64"]  # I don't think there are any OpenXR runtimes for macos

license = [
    "SPDX:GPL-3.0-or-later",
]

wheels = [
    "./wheels/pyopenxr-1.1.5101-py3-none-any.whl",
    "./wheels/pyopengl-3.1.10-py3-none-any.whl",
    "./wheels/glfw-2.10.0-py2.py27.py3.py30.py31.py32.py33.py34.py35.py36.py37.py38.p39.p310.p311.p312.p313-none-win_amd64.whl",
    "./wheels/glfw-2.10.0-py2.py27.py3.py30.py31.py32.py33.py34.py35.py36.py37.py38.p39.p310.p311.p312.p313-none-manylinux_2_28_x86_64.whl"
]

[build]
paths_exclude_pattern = [
  "images/",  # Stuff for readme
  "__pycache__/",
  ".*",
  "*.zip",
  "index.json",  # Extension repo stuff
]

[permissions]
files = "Load SteamVR controller and tracker models"  # Because of potential licensing issues, we cannot bundle them