name: package.yml
on:
  push:
    branches:
      - "main"
    tags:
      - "**"

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: setup variables
        run: echo "ZIP_NAME=tracking_toolkit-latest.zip" >> $GITHUB_ENV

      - name: checkout
        uses: actions/checkout@v4
      - name: download wheels
        run: |
          pip download --platform win_amd64 --only-binary :all: --dest wheels --no-deps -r requirements.txt
          pip download --platform manylinux_2_28_x86_64 --only-binary :all: --dest wheels --no-deps -r requirements.txt
      - name: package
        run: |
          zip -r ${{ env.ZIP_NAME }} ./* -x "images/*" "index.json"

      - name: create repository manifest
        run: |
          URL=https://github.com/ethanporcaro/tracking-toolkit/releases/latest/download/${{ env.ZIP_NAME }}
          FILESIZE=$(wc -c < ${{ env.ZIP_NAME }} | awk '{print $1}')
          SHA=sha256:$( openssl dgst -sha256 ${{ env.ZIP_NAME }}| awk '{print $2}')
          
          jq \
          --arg url "$URL" \
          --argjson size "$FILESIZE" \
          --arg sha "$SHA" \
          '.data[0] += {archive_url: $url, archive_size: $size, archive_hash: $sha}' repository_base.json > repository.json
          cat repository.json
          
      - name: Create release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            ${{ env.ZIP_NAME }}
            repository.json